Test extentions run parallel
mmatczuk/gohan pull request #1
Opened 2017-01-23 11:35 UTC by mmatczuk

This PR introduces parallel execution of extension tests. It solves a number of problems:

* removes use of `os.Chdir`, `os.Getwd`, `os.Chdir` anti pattern
* fixes multiple race conditions
* introduces a "thread local" version of manager singleton
* extends cli `test_ex` with `-p, -parallel` that defaults to number of cores available

Test machine: go version go1.7.4 linux/amd64, CPU Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz 4 cores

	time gohan test_ex -p 4 -c common/tests/esi-wan-gohan-js-tests-quiet.yaml
	real    5m17.199s
	user    15m51.424s
	sys     0m4.984s
	
	
	time gohan test_ex -p 8 -c common/tests/esi-wan-gohan-js-tests-quiet.yaml
	real    5m0.728s
	user    14m24.680s
	sys     0m4.172s
	
	
	time gohan test_ex -p 12 -c common/tests/esi-wan-gohan-js-tests-quiet.yaml
	real    5m14.172s
	user    16m42.888s
	sys     0m3.724s
	
	
	time gohan test_ex -c common/tests/esi-wan-gohan-js-tests-quiet.yaml
	real    5m47.579s
	user    7m48.424s
	sys     0m2.676s

So the improvement is not dramatic still the parallel run takes ~45sec less. Further improvements require fine tuning of the tests and test runs profiling.

2017-01-23 11:47 UTC, mmatczuk commented
I fixed race condition in sqlx https://github.com/jmoiron/sqlx/pull/272 it was merged fast so the vendored version could be updated WDYT.

2017-01-24 12:26 UTC, p-kozlowski requested changes

2017-01-24 12:26 UTC, p-kozlowski commented on db/sql/sql.go
> +var sqlqMu sync.Mutex
PR was merged, so remove

2017-01-24 12:26 UTC, p-kozlowski commented on extension/framework/framework.go
> +func shuffle(a []string) {
This could break existing order-dependent tests and (in case of a test failure) it'll make debugging harder. I suggest adding a separate command line switch, print the random generator seed value and allow to pass the seed as a separate command line argument. This way one could reproduce the failing case (of course only when there's only one worker).

2017-01-24 12:26 UTC, p-kozlowski commented on extension/framework/framework.go
> +			if i > maxIdx {
use more descriptive names like numTestFiles

2017-01-24 12:26 UTC, p-kozlowski commented on extension/framework/framework.go
> +			terr := runner.NewTestRunner(fileName, printAllLogs, testFilter).Run()
testErr

2017-01-24 12:26 UTC, p-kozlowski commented on extension/framework/runner/environment.go
> +		f := env.schemaPath(schemaIncludes)
f?

2017-01-24 12:26 UTC, p-kozlowski commented on extension/framework/runner/environment.go
> +func (env *Environment) schemaPath(s ...string) string {
s?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +	mu          sync.RWMutex
mu? gohan's local convention uses somethingMutex. same elsewhere

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +			s = append(s, schema)
s?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +	for i, m := range manager.policies {
i? m? s?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +		d := extensionData.(map[string](interface{}))
d?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +		m := gls.Get("manager")
m?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +	if !gohanFormatsRegistered {
how about sync.Once?

2017-01-24 12:26 UTC, p-kozlowski commented on schema/manager.go
> +var UseGls = false
There are several problems with this:
1. Gls suggest using of concrete implementation (github.com/tylerb/gls), not the usage intent: one manager per goroutine
2. It's a global variable
3. It's a global variable used in multithreaded context and not protected for synchronization
4. Changing it at runtime yields unpredictable behaviours

I suggest adding a simple layer of abstraction (perhaps a Strategy) to configure global instance/one instances per goroutine before the first call to GetManager.

2017-01-24 12:26 UTC, p-kozlowski commented on schema/url_test.go
> +			t.Error("Mismatch on", d)
[question] If the first test case fails, will you see the results for all other test cases?
If not, use https://onsi.github.io/ginkgo/#table-driven-tests

2017-01-24 12:26 UTC, p-kozlowski commented on schema/url_test.go
> +			t.Error("Mismatch on", d, actual)
as above

2017-01-24 12:26 UTC, p-kozlowski commented on vendor/github.com/ddliu/motto/motto.go
> +	// Onece a module is required by vm, the exported value is cached for
typo: Once

2017-01-24 12:26 UTC, p-kozlowski commented on vendor/github.com/ddliu/motto/motto.go
> +	"sync"
why don't we make a PR to motto with these changes?

2017-01-24 12:26 UTC, p-kozlowski commented on vendor/github.com/ddliu/motto/motto.go
> +	defer globalMu.RUnlock()
[question] sometimes you call Unlock explicitly, sometimes you use defer. why?

2017-01-24 12:29 UTC, mmatczuk commented
@p-kozlowski as for naming please take a look at this 

https://github.com/golang/go/wiki/CodeReviewComments#variable-names https://talks.golang.org/2014/names.slide#1

2017-01-24 12:38 UTC, mmatczuk commented on schema/url_test.go
> +			t.Error("Mismatch on", d)
Yes. 
Error is equivalent to Log followed by Fail.
Fail marks the function as having failed but continues execution.
https://golang.org/pkg/testing/#T.Error

2017-01-24 12:47 UTC, p-kozlowski commented
@mmatczuk I do not mind brevity, but expressions like "s[i] = m" are too much for me. I personally prefer readable and expressive code to unreadable.

2017-01-24 12:59 UTC, p-kozlowski commented on extension/framework/framework.go
> +	if workers <= 0 {
General remark: I can't find any tests of the new (parallel) flow.

2017-01-25 13:16 UTC, mmatczuk commented on schema/manager.go
> +	mu          sync.RWMutex
This is a golang wide naming convention, see in vendor and stdlib. BTW `grep -i` for mutex shows 2 variables

2017-01-25 13:43 UTC, p-kozlowski commented on schema/manager.go
> +	mu          sync.RWMutex
Exactly. Gohan uses "mutex", that is why I mentioned local convention (which should be favored IMO). git grep -E "sync\..*Mutex" shows mutex, mu, m, mtx and lock. But anyway, this is a minor issue.

2017-01-31 08:55 UTC, closed without merging